name       : libxdg-basedir
version    : 1.2.0
release    : 2
source     :
    - https://github.com/devnev/libxdg-basedir/archive/libxdg-basedir-1.2.0.tar.gz : 1c2b0032a539033313b5be2e48ddd0ae94c84faf21d93956d53562eef4614868
license    : MIT
component  : programming
summary    : An implementation of the XDG Base Directory specifications.
description: |
    An implementation of the XDG Base Directory specifications.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
